#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := Aruna-example

# Add Aruna library path to components
EXTRA_COMPONENT_DIRS += $(abspath ..)
EXTRA_COMPONENT_DIRS += $(PROJECT_PATH)/libs/MPUdriver
EXTRA_COMPONENT_DIRS += $(PROJECT_PATH)/libs/I2Cbus

include $(IDF_PATH)/make/project.mk
